apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo-basic
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
