apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: demo-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: amanve7/heartattack-frontend-service:latest
          ports:
            - containerPort: 80
