apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: YWFtbnZl          # base64 encoded 'amanve'
  mysql-password: QW1hbnZlcm1hQDIwMDE=  # base64 encoded 'Amanverma@2001'
