apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  namespace: demo-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: amanve7/heartattack-ml-service:latest
          ports:
            - containerPort: 5000
