apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: demo-basic
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      # Example: Parse multiline Java logs
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level} %{JAVACLASS:class} - %{GREEDYDATA:log_message}" }
        overwrite => [ "message" ]
      }

      date {
        match => [ "timestamp", "ISO8601" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.demo-basic.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }

      stdout { codec => rubydebug }
    }
